name: Rust

on:
  push:
    branches: [ "main", "rc/**/*" ]
  pull_request:
    branches: [ "main", "rc/**/*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install llvm-cov
      run: cargo install cargo-llvm-cov
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo llvm-cov --verbose

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Linter
      run: cargo clippy --verbose
  
  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Formatter
      run: cargo fmt --check
      
